language: bash

services:
  - docker

before_install:
  - docker build -t oskarv/snakemake-bg-tools .

script:
  - docker run -ti -v $(pwd):/data oskarv/snakemake-bg-tools sh -c "snakemake --version && Rscript /data/.r-travis-test.r"