language: bash

services:
  - docker

before_install:
  - docker build -t oskarv/snakemake-bg-tools .

script:
  - docker run -ti oskarv/snakemake-bg-tools sh -c "snakemake --version && Rscript .r-travis-test.r"